package service.models;

/**
 * Service-layer model representing a single physical copy of a book.
 *
 * <p>This class is used by the <strong>service</strong> and <strong>controller</strong>
 * layers and is intentionally decoupled from persistence concerns. It is converted
 * to and from {@code BookEntity} objects by {@code BookService}.</p>
 *
 * <p><strong>Design notes:</strong></p>
 * <ul>
 *   <li>Each {@code Book} represents one physical copy, not a title aggregate</li>
 *   <li>{@code id} is generated by the database and populated after creation</li>
 *   <li>{@code isbn} and {@code publicationYear} are optional fields</li>
 * </ul>
 */
public class Book {

    /**
     * Unique identifier for the book (maps to {@code books.id}).
     */
    private long id;

    /**
     * Book title (required).
     */
    private String title;

    /**
     * Book author (required).
     */
    private String author;

    /**
     * ISBN identifier (optional).
     */
    private String isbn;

    /**
     * Year the book was published (optional).
     */
    private Integer publicationYear;

    /**
     * No-argument constructor.
     *
     * <p>Required for frameworks, reflection-based tools, and general
     * object construction prior to field population.</p>
     */
    public Book() {}

    /**
     * Full constructor.
     *
     * <p>Typically used when converting from a persistence entity
     * or when reconstructing an existing book.</p>
     *
     * @param id               unique identifier
     * @param title            book title
     * @param author           book author
     * @param isbn             ISBN (nullable)
     * @param publicationYear  publication year (nullable)
     */
    public Book(long id, String title, String author, String isbn, Integer publicationYear) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.isbn = isbn;
        this.publicationYear = publicationYear;
    }

    /**
     * Constructor without an ID.
     *
     * <p>Used when creating a new book before it has been persisted.
     * The ID is generated by the database and later injected by the service layer.</p>
     *
     * @param title            book title
     * @param author           book author
     * @param isbn             ISBN (nullable)
     * @param publicationYear  publication year (nullable)
     */
    public Book(String title, String author, String isbn, Integer publicationYear) {
        this.title = title;
        this.author = author;
        this.isbn = isbn;
        this.publicationYear = publicationYear;
    }

    /**
     * Returns the book identifier.
     *
     * @return book id
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the book identifier.
     *
     * <p>Typically called by the service layer after persistence.</p>
     *
     * @param id generated identifier
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the book title.
     *
     * @return title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the book title.
     *
     * @param title non-blank title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the book author.
     *
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the book author.
     *
     * @param author non-blank author
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Returns the ISBN value.
     *
     * @return ISBN or {@code null}
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the ISBN value.
     *
     * @param isbn ISBN string or {@code null}
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Returns the publication year.
     *
     * @return publication year or {@code null}
     */
    public Integer getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the publication year.
     *
     * @param publicationYear year or {@code null}
     */
    public void setPublicationYear(Integer publicationYear) {
        this.publicationYear = publicationYear;
    }

    /**
     * Returns a human-readable string representation of the book.
     *
     * <p>Optional fields are only included if present.</p>
     *
     * @return formatted book string
     */
    @Override
    public String toString() {
        return "Book { " +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                (isbn != null ? ", isbn='" + isbn + '\'' : "") +
                (publicationYear != null ? ", year=" + publicationYear : "") +
                " }";
    }
}
