package service.models;

import java.time.LocalDate;

/**
 * Service-layer model representing the loan of a book to a member.
 *
 * <p>This class acts as a <strong>junction model</strong> between books and members
 * in the service and controller layers. It mirrors the structure of the
 * {@code loans} table but is intentionally decoupled from persistence concerns.</p>
 *
 * <p><strong>Key characteristics:</strong></p>
 * <ul>
 *   <li>Each {@code Loan} links exactly one book to one member</li>
 *   <li>{@code checkoutDate} and {@code dueDate} are required</li>
 *   <li>{@code returnDate} is optional and {@code null} while the loan is active</li>
 *   <li>{@code id} is generated by the database and set after persistence</li>
 * </ul>
 */
public class Loan {

    /**
     * Unique identifier for the loan (maps to {@code loans.id}).
     */
    private long id;

    /**
     * Identifier of the borrowed book (maps to {@code books.id}).
     */
    private long bookId;

    /**
     * Identifier of the borrowing member (maps to {@code members.id}).
     */
    private long memberId;

    /**
     * Date the book was checked out (required).
     */
    private LocalDate checkoutDate;

    /**
     * Date the book is due to be returned (required).
     */
    private LocalDate dueDate;

    /**
     * Date the book was returned, or {@code null} if the loan is still active.
     */
    private LocalDate returnDate;

    /**
     * No-argument constructor.
     *
     * <p>Required for frameworks, reflection, and incremental population
     * of fields prior to persistence.</p>
     */
    public Loan() {}

    /**
     * Full constructor.
     *
     * <p>Typically used when converting from a persistence entity or
     * reconstructing an existing loan.</p>
     *
     * @param id            loan identifier
     * @param bookId        associated book identifier
     * @param memberId      associated member identifier
     * @param checkoutDate  checkout date (non-null)
     * @param dueDate       due date (non-null)
     * @param returnDate    return date, or {@code null} if active
     */
    public Loan(long id,
                long bookId,
                long memberId,
                LocalDate checkoutDate,
                LocalDate dueDate,
                LocalDate returnDate) {
        this.id = id;
        this.bookId = bookId;
        this.memberId = memberId;
        this.checkoutDate = checkoutDate;
        this.dueDate = dueDate;
        this.returnDate = returnDate;
    }

    /**
     * Constructor for creating a new loan before persistence.
     *
     * <p>The {@code id} is generated by the database and populated by
     * the service layer after saving.</p>
     *
     * @param bookId        associated book identifier
     * @param memberId      associated member identifier
     * @param checkoutDate  checkout date (non-null)
     * @param dueDate       due date (non-null)
     * @param returnDate    return date, or {@code null} if active
     */
    public Loan(long bookId,
                long memberId,
                LocalDate checkoutDate,
                LocalDate dueDate,
                LocalDate returnDate) {
        this.bookId = bookId;
        this.memberId = memberId;
        this.checkoutDate = checkoutDate;
        this.dueDate = dueDate;
        this.returnDate = returnDate;
    }

    /**
     * Returns the loan identifier.
     *
     * @return loan id
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the loan identifier.
     *
     * <p>Typically called by the service layer after persistence.</p>
     *
     * @param id generated loan identifier
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the associated book identifier.
     *
     * @return book id
     */
    public long getBookId() {
        return bookId;
    }

    /**
     * Sets the associated book identifier.
     *
     * @param bookId book id
     */
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    /**
     * Returns the associated member identifier.
     *
     * @return member id
     */
    public long getMemberId() {
        return memberId;
    }

    /**
     * Sets the associated member identifier.
     *
     * @param memberId member id
     */
    public void setMemberId(long memberId) {
        this.memberId = memberId;
    }

    /**
     * Returns the checkout date.
     *
     * @return checkout date
     */
    public LocalDate getCheckoutDate() {
        return checkoutDate;
    }

    /**
     * Sets the checkout date.
     *
     * @param checkoutDate non-null checkout date
     */
    public void setCheckoutDate(LocalDate checkoutDate) {
        this.checkoutDate = checkoutDate;
    }

    /**
     * Returns the due date.
     *
     * @return due date
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * Sets the due date.
     *
     * @param dueDate non-null due date
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * Returns the return date.
     *
     * @return return date, or {@code null} if the loan is still active
     */
    public LocalDate getReturnDate() {
        return returnDate;
    }

    /**
     * Sets the return date.
     *
     * @param returnDate return date, or {@code null}
     */
    public void setReturnDate(LocalDate returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * Returns a human-readable string representation of the loan.
     *
     * <p>Includes key identifiers and dates, and explicitly shows whether
     * the loan has been returned.</p>
     *
     * @return formatted loan string
     */
    @Override
    public String toString() {
        return "Loan { " +
                "id=" + id +
                ", bookId=" + bookId +
                ", memberId=" + memberId +
                ", checkoutDate=" + checkoutDate +
                ", dueDate=" + dueDate +
                (returnDate != null ? ", returnDate=" + returnDate : ", returnDate=null") +
                " }";
    }
}
