package service.models;

/**
 * Service-layer model representing a library member.
 *
 * <p>This class is used by the controller and service layers to represent
 * a person who can borrow books from the library. It mirrors the structure
 * of the {@code members} table but is intentionally decoupled from
 * persistence concerns.</p>
 *
 * <p><strong>Key characteristics:</strong></p>
 * <ul>
 *   <li>{@code id} is generated by the database and assigned after persistence</li>
 *   <li>{@code name} is required</li>
 *   <li>{@code email} is optional but may be unique if provided</li>
 *   <li>{@code phone} is optional</li>
 * </ul>
 */
public class Member {

    /**
     * Unique identifier for the member (maps to {@code members.id}).
     */
    private long id;

    /**
     * Full name of the member (required).
     */
    private String name;

    /**
     * Email address of the member.
     * <p>Optional, but typically unique when present.</p>
     */
    private String email;

    /**
     * Phone number of the member.
     * <p>Optional field used for contact purposes.</p>
     */
    private String phone;

    /**
     * No-argument constructor.
     *
     * <p>Required for frameworks, reflection, and incremental population
     * of fields prior to persistence.</p>
     */
    public Member() {}

    /**
     * Full constructor.
     *
     * <p>Typically used when converting from a persistence entity or
     * reconstructing an existing member.</p>
     *
     * @param id     member identifier
     * @param name   member name
     * @param email  email address (nullable)
     * @param phone  phone number (nullable)
     */
    public Member(long id, String name, String email, String phone) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
    }

    /**
     * Constructor for creating a new member before persistence.
     *
     * <p>The {@code id} is generated by the database and set by the
     * service layer after saving.</p>
     *
     * @param name   member name
     * @param email  email address (nullable)
     * @param phone  phone number (nullable)
     */
    public Member(String name, String email, String phone) {
        this.name = name;
        this.email = email;
        this.phone = phone;
    }

    /**
     * Returns the member identifier.
     *
     * @return member id
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the member identifier.
     *
     * <p>Typically called by the service layer after persistence.</p>
     *
     * @param id generated member identifier
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the member's name.
     *
     * @return member name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the member's name.
     *
     * @param name non-null member name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the member's email address.
     *
     * @return email address, or {@code null} if not provided
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the member's email address.
     *
     * @param email email address, or {@code null}
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the member's phone number.
     *
     * @return phone number, or {@code null} if not provided
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the member's phone number.
     *
     * @param phone phone number, or {@code null}
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns a human-readable string representation of the member.
     *
     * <p>Optional fields are included only when present to keep output concise.</p>
     *
     * @return formatted member string
     */
    @Override
    public String toString() {
        return "Member { " +
                "id=" + id +
                ", name='" + name + '\'' +
                (email != null ? ", email='" + email + '\'' : "") +
                (phone != null ? ", phone='" + phone + '\'' : "") +
                " }";
    }
}
