// BookEntity.java
package repository.entities;

import java.util.Objects;

/**
 * Represents a single row in the {@code books} table.
 *
 * <p>Each {@code BookEntity} corresponds to exactly one physical copy of a book
 * stored in the database. This class is a persistence-layer representation and
 * should not contain business logic.</p>
 *
 * <p><strong>Layering:</strong> This entity is used by the DAO layer to map
 * database rows to Java objects. It may be converted to a service-layer model
 * (e.g., {@code Book}) before being exposed to controllers.</p>
 *
 * <p><strong>Nullability:</strong>
 * <ul>
 *   <li>{@code isbn} may be {@code null}</li>
 *   <li>{@code publicationYear} may be {@code null}</li>
 * </ul>
 * These constraints mirror the database schema.</p>
 */
public class BookEntity {

    /**
     * Primary key for the book record.
     * <p>Maps to a {@code BIGINT} column in PostgreSQL and is generated by the database.</p>
     */
    private long id;

    /**
     * Book title (NOT NULL in the database).
     */
    private String title;

    /**
     * Book author (NOT NULL in the database).
     */
    private String author;

    /**
     * ISBN value for the book.
     * <p>This field is optional and may be {@code null}.</p>
     */
    private String isbn;

    /**
     * Year the book was published.
     * <p>This field is optional and may be {@code null}.</p>
     */
    private Integer publicationYear;

    /**
     * No-argument constructor.
     *
     * <p>Required for frameworks, reflection, and manual property setting.</p>
     */
    public BookEntity() { }

    /**
     * Full constructor including the primary key.
     *
     * <p>Typically used when hydrating an entity from the database.</p>
     *
     * @param id              database-generated primary key
     * @param title           book title
     * @param author          book author
     * @param isbn            ISBN (nullable)
     * @param publicationYear publication year (nullable)
     */
    public BookEntity(long id, String title, String author, String isbn, Integer publicationYear) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.isbn = isbn;
        this.publicationYear = publicationYear;
    }

    /**
     * Convenience constructor for insert operations.
     *
     * <p>The {@code id} is set to {@code 0} and is expected to be populated
     * by the database upon insert.</p>
     *
     * @param title           book title
     * @param author          book author
     * @param isbn            ISBN (nullable)
     * @param publicationYear publication year (nullable)
     */
    public BookEntity(String title, String author, String isbn, Integer publicationYear) {
        this(0L, title, author, isbn, publicationYear);
    }

    /**
     * Returns the database ID of this book.
     *
     * @return book ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the database ID of this book.
     *
     * <p>This is typically called by the DAO after an insert operation.</p>
     *
     * @param id database-generated ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the book title.
     *
     * @return title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the book title.
     *
     * @param title book title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the book author.
     *
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the book author.
     *
     * @param author book author
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Returns the ISBN value.
     *
     * @return ISBN, or {@code null} if not provided
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the ISBN value.
     *
     * @param isbn ISBN value, or {@code null}
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Returns the publication year.
     *
     * @return publication year, or {@code null}
     */
    public Integer getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the publication year.
     *
     * @param publicationYear publication year, or {@code null}
     */
    public void setPublicationYear(Integer publicationYear) {
        this.publicationYear = publicationYear;
    }

    /**
     * Returns a string representation of this entity.
     *
     * <p>Intended primarily for debugging and logging.</p>
     *
     * @return string representation of the book entity
     */
    @Override
    public String toString() {
        return "BookEntity{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                ", isbn='" + isbn + '\'' +
                ", publicationYear=" + publicationYear +
                '}';
    }

    /**
     * Compares this entity to another object for equality.
     *
     * <p>All fields are compared, including the primary key.</p>
     *
     * @param o object to compare against
     * @return {@code true} if equal, otherwise {@code false}
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BookEntity)) return false;
        BookEntity that = (BookEntity) o;
        return id == that.id &&
                Objects.equals(title, that.title) &&
                Objects.equals(author, that.author) &&
                Objects.equals(isbn, that.isbn) &&
                Objects.equals(publicationYear, that.publicationYear);
    }

    /**
     * Computes a hash code based on all fields.
     *
     * @return hash code for this entity
     */
    @Override
    public int hashCode() {
        return Objects.hash(id, title, author, isbn, publicationYear);
    }
}
