package repository.entities;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Represents a single row in the {@code loans} table.
 *
 * <p>This entity models a book loan and acts as a junction between
 * {@code books} and {@code members}. Each {@code LoanEntity} represents
 * one checkout event for a specific book by a specific member.</p>
 *
 * <p><strong>Lifecycle:</strong>
 * <ul>
 *   <li>A loan is <em>active</em> when {@code returnDate == null}</li>
 *   <li>A loan is <em>returned</em> when {@code returnDate != null}</li>
 * </ul>
 * </p>
 *
 * <p><strong>Layering:</strong> This class belongs to the persistence layer.
 * It is used by DAOs to map database rows to Java objects and is typically
 * converted to a service-layer model (e.g., {@code Loan}) before being
 * exposed to controllers.</p>
 */
public class LoanEntity {

    /**
     * Primary key for the loan record.
     *
     * <p>Maps to a {@code BIGINT GENERATED ALWAYS AS IDENTITY} column
     * in PostgreSQL and is generated by the database.</p>
     */
    private long id;

    /**
     * Foreign key referencing {@code books.id}.
     *
     * <p>Identifies which book is being loaned.</p>
     */
    private long bookId;

    /**
     * Foreign key referencing {@code members.id}.
     *
     * <p>Identifies which member checked out the book.</p>
     */
    private long memberId;

    /**
     * Date the book was checked out.
     *
     * <p>This field is required and must not be {@code null}.</p>
     */
    private LocalDate checkoutDate;

    /**
     * Date the book is due to be returned.
     *
     * <p>This field is required and must not be {@code null}.
     * Business rules typically enforce {@code dueDate >= checkoutDate}.</p>
     */
    private LocalDate dueDate;

    /**
     * Date the book was actually returned.
     *
     * <p>This field is {@code null} while the loan is active.</p>
     */
    private LocalDate returnDate;

    /**
     * No-argument constructor.
     *
     * <p>Required for frameworks, reflection, and manual property assignment.</p>
     */
    public LoanEntity() { }

    /**
     * Full constructor including the primary key.
     *
     * <p>Typically used when hydrating a {@code LoanEntity} from the database.</p>
     *
     * @param id           database-generated primary key
     * @param bookId       referenced book ID
     * @param memberId     referenced member ID
     * @param checkoutDate checkout date (not null)
     * @param dueDate      due date (not null)
     * @param returnDate   return date (nullable)
     */
    public LoanEntity(long id,
                      long bookId,
                      long memberId,
                      LocalDate checkoutDate,
                      LocalDate dueDate,
                      LocalDate returnDate) {
        this.id = id;
        this.bookId = bookId;
        this.memberId = memberId;
        this.checkoutDate = checkoutDate;
        this.dueDate = dueDate;
        this.returnDate = returnDate;
    }

    /**
     * Convenience constructor for insert operations.
     *
     * <p>The {@code id} is initialized to {@code 0} and is expected
     * to be populated by the database upon insert.</p>
     *
     * @param bookId       referenced book ID
     * @param memberId     referenced member ID
     * @param checkoutDate checkout date (not null)
     * @param dueDate      due date (not null)
     * @param returnDate   return date (nullable)
     */
    public LoanEntity(long bookId,
                      long memberId,
                      LocalDate checkoutDate,
                      LocalDate dueDate,
                      LocalDate returnDate) {
        this(0L, bookId, memberId, checkoutDate, dueDate, returnDate);
    }

    /**
     * Returns the loan ID.
     *
     * @return loan ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the loan ID.
     *
     * <p>This is typically called by the DAO after an insert operation.</p>
     *
     * @param id database-generated ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the referenced book ID.
     *
     * @return book ID
     */
    public long getBookId() {
        return bookId;
    }

    /**
     * Sets the referenced book ID.
     *
     * @param bookId book ID
     */
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    /**
     * Returns the referenced member ID.
     *
     * @return member ID
     */
    public long getMemberId() {
        return memberId;
    }

    /**
     * Sets the referenced member ID.
     *
     * @param memberId member ID
     */
    public void setMemberId(long memberId) {
        this.memberId = memberId;
    }

    /**
     * Returns the checkout date.
     *
     * @return checkout date
     */
    public LocalDate getCheckoutDate() {
        return checkoutDate;
    }

    /**
     * Sets the checkout date.
     *
     * @param checkoutDate checkout date (not null)
     */
    public void setCheckoutDate(LocalDate checkoutDate) {
        this.checkoutDate = checkoutDate;
    }

    /**
     * Returns the due date.
     *
     * @return due date
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * Sets the due date.
     *
     * @param dueDate due date (not null)
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * Returns the return date.
     *
     * @return return date, or {@code null} if the loan is still active
     */
    public LocalDate getReturnDate() {
        return returnDate;
    }

    /**
     * Sets the return date.
     *
     * @param returnDate return date, or {@code null}
     */
    public void setReturnDate(LocalDate returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * Returns a string representation of this loan entity.
     *
     * <p>Intended for debugging and logging purposes.</p>
     *
     * @return string representation of the loan
     */
    @Override
    public String toString() {
        return "LoanEntity{" +
                "id=" + id +
                ", bookId=" + bookId +
                ", memberId=" + memberId +
                ", checkoutDate=" + checkoutDate +
                ", dueDate=" + dueDate +
                ", returnDate=" + returnDate +
                '}';
    }

    /**
     * Compares this loan entity to another object for equality.
     *
     * <p>All fields are compared, including the primary key.</p>
     *
     * @param o object to compare against
     * @return {@code true} if equal, otherwise {@code false}
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LoanEntity)) return false;
        LoanEntity that = (LoanEntity) o;
        return id == that.id &&
                bookId == that.bookId &&
                memberId == that.memberId &&
                Objects.equals(checkoutDate, that.checkoutDate) &&
                Objects.equals(dueDate, that.dueDate) &&
                Objects.equals(returnDate, that.returnDate);
    }

    /**
     * Computes a hash code based on all fields.
     *
     * @return hash code for this entity
     */
    @Override
    public int hashCode() {
        return Objects.hash(id, bookId, memberId, checkoutDate, dueDate, returnDate);
    }
}
