package repository.entities;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Represents a single row in the "loans" table.
 * Acts as a junction entity between books and members.
 */
public class LoanEntity {

    private long id;                // BIGINT GENERATED ALWAYS AS IDENTITY
    private long bookId;            // FK → books.id
    private long memberId;          // FK → members.id
    private LocalDate checkoutDate; // NOT NULL
    private LocalDate dueDate;      // NOT NULL
    private LocalDate returnDate;   // nullable

    public LoanEntity() { }

    public LoanEntity(long id,
                      long bookId,
                      long memberId,
                      LocalDate checkoutDate,
                      LocalDate dueDate,
                      LocalDate returnDate) {
        this.id = id;
        this.bookId = bookId;
        this.memberId = memberId;
        this.checkoutDate = checkoutDate;
        this.dueDate = dueDate;
        this.returnDate = returnDate;
    }

    // Convenience constructor for inserts (id generated by DB)
    public LoanEntity(long bookId,
                      long memberId,
                      LocalDate checkoutDate,
                      LocalDate dueDate,
                      LocalDate returnDate) {
        this(0L, bookId, memberId, checkoutDate, dueDate, returnDate);
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getBookId() {
        return bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public long getMemberId() {
        return memberId;
    }

    public void setMemberId(long memberId) {
        this.memberId = memberId;
    }

    public LocalDate getCheckoutDate() {
        return checkoutDate;
    }

    public void setCheckoutDate(LocalDate checkoutDate) {
        this.checkoutDate = checkoutDate;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public LocalDate getReturnDate() {
        return returnDate;
    }

    public void setReturnDate(LocalDate returnDate) {
        this.returnDate = returnDate;
    }

    @Override
    public String toString() {
        return "LoanEntity{" +
                "id=" + id +
                ", bookId=" + bookId +
                ", memberId=" + memberId +
                ", checkoutDate=" + checkoutDate +
                ", dueDate=" + dueDate +
                ", returnDate=" + returnDate +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LoanEntity)) return false;
        LoanEntity that = (LoanEntity) o;
        return id == that.id &&
                bookId == that.bookId &&
                memberId == that.memberId &&
                Objects.equals(checkoutDate, that.checkoutDate) &&
                Objects.equals(dueDate, that.dueDate) &&
                Objects.equals(returnDate, that.returnDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, bookId, memberId, checkoutDate, dueDate, returnDate);
    }
}
